# VCD to DataFrame Conversion Libraries

## Main Goal

### Technical Description

Create libraries that convert VCD (Value Change Dump) files into data frames that can be analyzed using languages such as Python or R.

### Human-Readable Description

Create tools that turn raw hardware simulation data into spreadsheet-like tables that are easier to analyze using data science tools.

The goal is to:

* Make hardware simulation data easier to work with
* Allow researchers to use common data science tools on hardware traces
* Support both small and large hardware designs without excessive computation

---

# Purpose

## Technical Description

Develop frameworks that scale to hardware designs of any size without causing excessive computational overhead.

## Human-Readable Description

The system is designed so that even very large hardware simulations can be processed efficiently.

Instead of overwhelming the computer with huge trace files, the framework organizes and simplifies the data so it can be analyzed using tools like:

* R
* Python pandas
* Apache Spark

---

# Background Concepts

## HDL (Hardware Description Languages)

### Definition

Hardware Description Languages (HDLs) allow engineers to design hardware systems using code.

### Human-Readable Description

HDLs are programming-like languages used to describe how hardware should behave.

Examples include:

* Verilog
* VHDL

These languages are used to:

* Design processors
* Create circuits
* Simulate hardware behavior

---

# VCD (Value Change Dumps)

## Definition

VCD files are ASCII-based dump files generated by hardware simulation tools.

They record changes in hardware signal values over time during simulation.

## Human-Readable Description

A VCD file acts like a recording of what happened inside a hardware simulation.

It stores:

* Which registers changed
* When they changed
* What values they changed to

The most important information is usually the “value change” section, which tracks when a signal changes value, such as:

* 0 → 1
* 1 → 0

---

# How VCD Files Are Generated

VCD files are typically produced using:

* A hardware design
* A testbench
* A simulator

## Definitions

### Hardware Design

The actual hardware system being tested.

### Testbench

A controlled testing environment used to verify hardware behavior.

### Simulator

Software that executes the hardware design and produces execution traces.

---

# vcd2d Library

## Definition

vcd2d is a library designed to convert VCD files into data frames.

## Supported Platforms

vcd2d supports:

* R data frames
* Python pandas DataFrames
* Apache Spark DataFrames

---

# How the System Works

## Input

A single string containing the file path to a `.vcd` file.

Example:

```python
"trace.vcd"
```

---

## Output

The library outputs either:

* A Python pandas DataFrame
* An R list of objects of class `data.frame`

The resulting structure stores signal values over time.

---

# Data Organization

## Rows

Each row represents a register or signal.

## Columns

Each column represents a time point during simulation.

This creates a table-like structure where hardware activity can be analyzed using data science methods.

---

# Handling Non-Numeric Values

## Problem

Some registers do not contain simple binary numeric values.

## Solution

If a register does not contain numeric values such as:

* 0
* 1

then the value is manually converted to:

```text
-1
```

This simplifies downstream analysis and keeps the dataset numerically consistent.

---

# Duplicate Register Handling

## Problem

Some VCD files contain registers with duplicate names.

This can create:

* Data duplication
* Ambiguous results
* Larger memory usage

## Solution

Duplicate register names are removed before conversion.

This reduces redundancy and improves efficiency.

---

# Scalability Goals

The framework is designed to:

* Work on both small and large hardware designs
* Reduce unnecessary computation
* Support distributed processing systems such as Apache Spark

This makes it possible to analyze very large hardware simulations more efficiently.

---

# General Notes and Definitions

## Acronyms

### VCD

Value Change Dump

### HDL

Hardware Description Language

### ASF / Apache Spark

A distributed computing engine used for large-scale data processing on:

* Single-node machines
* Multi-node clusters

---

# Key Takeaways

* VCD files store hardware signal changes over time.
* vcd2d converts VCD files into data-frame structures.
* The library supports R, Python pandas, and Apache Spark.
* The framework is designed for scalability and efficient computation.
* Hardware simulation traces become easier to analyze using standard data science tools.
